name: sand_piles_app
description: Sand piles demo app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  main_thread_processor:
    path: ../main_thread_processor
  sand_piles:
    path: ../sand_piles

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
